[package]
name = "kernel"
version = "0.1.0"

[dependencies]
sys_util = { path = "../sys_util" }
memory_model = { path = "../memory_model" }
x86_64 = { path = "../x86_64" }
logger = { path = "../logger" }
